### ISSUE TITLE
Add profile pictures

### ISSUE THREAD

**Issue by rapPayne** [rapPayne/edp_2024_09_people_picker#11]
1. Add a folder to the server under static to hold all images.

2. Edit the JSON data to give each person their own jpg/gif/png file. You don't have to provide the image file. Just give each person a name.

3. Change the code to read that image filename and render that image instead of the hardcoded placeholder.

4. Add code to say if the image doesn't exist, draw a placeholder image instead.

**Comment by bennyleemn** [comment]
id like to try this one

**Comment by rapPayne** [comment]
@bennyleemn You seem super busy. I'll take this one myself. We'll fix you up with another one later.

**Comment by rapPayne** [comment]
Closed by commit 05660d4c083f8674fac67f13d0622aaed0349285
