### ISSUE TITLE
Add a Mongo database

### ISSUE THREAD

**Issue by rapPayne** [rapPayne/edp_2024_09_people_picker#12]
This is prep for reading the data from mongo instead of the lame flat JSON file we're using now.

Add a "data" folder to the project. Add a "db" folder under that.

Add a script in package.json to start up the database server. (ie. make `npm run start-db` or something work).

IMPORTANT! Add `data` to .gitignore.

**Comment by jac00012** [comment]
ill give this one a shot

**Comment by rapPayne** [comment]
Way to go, Jeff!

**Comment by jac00012** [comment]
Hi Rap! When I'm working on this should i be on my own branch (locally)? and when I'm ready to push should i just leave it on that branch or merge it first then push?

**Comment by rapPayne** [comment]
Great question. Branch locally, then merge back to main, then push to YOUR forked repo. Then go to github.com on your repo and create the pull request.
