### ISSUE TITLE
Add a defer functionality

### ISSUE THREAD

**Issue by rapPayne** [rapPayne/edp_2024_09_people_picker#15]
Add a defer button. When hit, it should move the currently selected person to a 'deferredPeople' list.

The 'choose' button should then be modified. When the unchosenPeople list becomes empty, we should begin pulling from the deferredPeople list. You may move them to unchosenPeople or you may change the list that chooseRandomPerson() pulls from. Up to you.

**Comment by vxie0119** [comment]
I can take this

**Comment by rapPayne** [comment]
Closed by #17
