### ISSUE TITLE
Style the app

### ISSUE THREAD

**Issue by rapPayne** [rapPayne/edp_2024_09_people_picker#3]
Add a CSS file for the site look and feel.

**Comment by rapPayne** [comment]
Okay styling was added, but it could be much better. Make it look better.

**Comment by victoriamertens** [comment]
I can try this one :)

**Comment by bennyleemn** [comment]
Id like to take this one. If i need help, ill post out.

**Comment by bennyleemn** [comment]
you beat me to it

**Comment by victoriamertens** [comment]
I mean, I only did a certain amount of styling to it. There is always room for more styling. If you want to add more, feel free. I have an PR up now so once Rap merges I think you can probably add more styling if you want.
